n1 = input('Digite algo:')
print('O tipo primitivo desse valor é', type(n1))
print('Só tem espaços', n1.isspace())
print('É um número?', n1.isnumeric())
print('É alfabético?', n1.isalpha())
print('É alfanumerico?', n1.isalnum())
print('Está me maiúsculo?', n1.islower())
print('Esta em minusculo?', n1.isupper())
